name: finben_vllm3
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.44=h1aa0949_5
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - airportsdata==20250909
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bitsandbytes==0.49.0
      - blake3==1.0.8
      - certifi==2025.11.12
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.2.1
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - compressed-tensors==0.8.1
      - dataproperty==1.1.0
      - datasets==4.4.1
      - deepspeed==0.18.3
      - depyf==0.18.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - einops==0.8.1
      - evaluate==0.4.6
      - exceptiongroup==1.3.0
      - fastapi==0.121.2
      - filelock==3.19.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gguf==0.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - interegular==0.3.3
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - jsonlines==4.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lark==1.3.1
      - lm-eval==0.4.7
      - lm-format-enforcer==0.10.12
      - lxml==6.0.2
      - markupsafe==2.1.5
      - mbstrdecoder==1.1.4
      - mistral-common==1.8.5
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.19.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.13.0
      - nltk==3.9.2
      - numexpr==2.14.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==2.7.2
      - opencv-python-headless==4.11.0.86
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==25.0
      - pandas==2.3.3
      - partial-json-parser==0.2.1.1.post6
      - pathvalidate==3.3.1
      - peft==0.5.0
      - pillow==11.3.0
      - portalocker==3.2.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.4.1
      - protobuf==6.33.1
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pybind11==3.0.1
      - pycountry==24.6.1
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pytablewriter==1.2.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - ray==2.51.1
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rouge-score==0.1.2
      - rpds-py==0.28.0
      - sacrebleu==2.5.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - six==1.17.0
      - sniffio==1.3.1
      - sqlitedict==2.1.0
      - starlette==0.49.3
      - sympy==1.13.1
      - tabledata==1.3.4
      - tabulate==0.9.0
      - tcolorpy==0.1.7
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.21.4
      - torch==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - tqdm-multiprocess==0.0.11
      - transformers==4.51.3
      - triton==3.1.0
      - typepy==1.3.4
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - vllm==0.6.5
      - watchfiles==1.1.1
      - websockets==15.0.1
      - word2number==1.1
      - xformers==0.0.28.post3
      - xgrammar==0.1.27
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: /home/lm2445/.conda/envs/finben_vllm3
